---
swagger: "2.0"
info:
  description: "No description"
  version: "1.0.0"
  title: ""
  contact: {}
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /token:
    post:
      summary: "Log in with email and password"
      consumes:
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "grant_type"
        in: "formData"
        required: true
        type: "string"
        enum:
        - "password"
        pattern: "password"
      - name: "username"
        in: "formData"
        required: true
        type: "string"
        description: "The email address the user signed up with."
        x-example: "john@mccla.ne"
      - name: "password"
        in: "formData"
        required: true
        type: "string"
        x-example: "this is a bad password"
      responses:
        200:
          description: "Status 200"
  /users:
    post:
      summary: "Create User"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/Create%20User%20Request"
      responses:
        200:
          description: "Status 200"
  /users/me:
    get:
      summary: "Retrieve current user"
      parameters: []
      responses:
        200:
          description: "A user object"
  /users/me/password:
    put:
      summary: "Change password"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
          required:
          - "password"
          properties:
            password:
              type: "string"
              example: "my new password"
      responses:
        204:
          description: "Status 204"
definitions:
  Create User Request:
    type: "object"
    required:
    - "email"
    - "name"
    - "password"
    properties:
      name:
        type: "string"
        example: "John McClane"
      email:
        type: "string"
        example: "john@mccla.ne"
      password:
        type: "string"
        example: "this is a bad password"
    example: "{ \"name\": \"John McClane\", \"email\": \"john@mccla.ne\", \"password\": \"this is a bad password\" }"
